-- OBSOLÈTE — NE PAS EXÉCUTER.
--
-- Ce fichier partait d'un mauvais postulat (aucun système d'argent
-- n'existait côté jeu). En réalité le jeu a déjà public.player_wallets
-- (credits) + public.player_transactions depuis longtemps.
--
-- Remplacé par : SUPABASE_UPDATE_BOT_BANQUE_DISCORD.sql (à la racine du
-- dépôt du bot), qui se branche sur ce système existant au lieu d'en
-- recréer un.
--
-- Tu peux supprimer ce fichier (SUPABASE_UPDATE_0056_BANQUE_DISCORD.sql).
